services:
  devcontainer:
    build: 
      context: .
      args:
        UV_VERSION: "0.5.13"
        DEBIAN_VERSION: "bookworm"
    environment:
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@localhost:5432/prefect
      - PREFECT_API_DATABASE_ECHO=False
      - PREFECT_DEFAULT_RESULT_STORAGE_BLOCK=s3-bucket/prefect-results-storage-bucket 
      - PREFECT_RESULTS_PERSIST_BY_DEFAULT=True
          
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
  postgres:
      image: postgres:17.2
      environment:
          - POSTGRES_USER=prefect
          - POSTGRES_PASSWORD=prefect
          - POSTGRES_DB=prefect
      volumes:
          - prefect-postgres:/var/lib/postgresql/data

      network_mode: service:devcontainer

  prefect-server:
    image: prefecthq/prefect:3.1.14-python3.12
    entrypoint: 
      - prefect
      - server
      - start

    network_mode: service:devcontainer

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniopassword
      MINIO_VOLUMES: "/mnt/data"

    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - prefect-minio:/mnt/data

    command: server --console-address ":9001"
    network_mode: service:devcontainer



volumes:
    prefect-postgres:
        name: prefect-postgres
    prefect-minio:
        name: prefect-minio
